### ISSUE TITLE
Не работает с бухгалтерией 3.0 базовая

### ISSUE THREAD

**Issue by vguns** [retailcrm/1C-configuration#1]
**Загрузить заказы:**
получение элемента по индексу для значения не определено
{Обработка.IntaroШаблонноеРешение.МодульОбъекта(457)}: Получение элемента по индексу для значения не определено
		искПарт = Справочники[Конфа["СправочникПартнеров"]].СоздатьЭлемент();
**выгрузка каталога:**
итератор для значения не определен
{Обработка.IntaroШаблонноеРешение.МодульОбъекта(1682)}: Итератор для значения не определен
	Для каждого стр Из Рез Цикл

**Comment by gwinn** [comment]
Шаблонное решение настраивалось на конфигурации "Управление торговлей" и предназначено для установки на версию "Проф", но не на "Бухгалтерия базовая". Шаблонное решение необходимо дорабатывать под другие версии конфигураций.
