### ISSUE TITLE
Обновление обработки до новой версии

### ISSUE THREAD

**Issue by maxdmtrv** [retailcrm/1C-configuration#11]
Добавьте в мануал процесс обновления обработки до новой версии, пожалуйста.

**Comment by Marina48** [comment]
Добрый день!
Для того чтобы обновить модуль до новой версии,  необходимо воспользоваться командой "Конфигурация - Сравнить, объединить с конфигурацией из файла...". 
Механизм сравнения и объединения конфигураций описан на сайте 1С:ИТС (https://its.1c.ru/db/v838doc#bookmark:dev:TI000001073) и на сайте 1С (http://v8.1c.ru/overview/Term_000000291.htm).

Если Ваше интеграционное решение было доработано и отличается от шаблонного модуля - необходимо будет решить возникшие конфликты. 
Если у Вас установлен шаблонный модуль, необходимо будет обновить изменившиеся объекты конфигурации. В данной версии изменилась обработка RetailCRMШаблонноеРешение (модуль объекта, формы и реквизиты).

Так же в конфигурации шаблонного решения присутствуют типовые объекты (Справочники: Номенклатура, ВидыЦен, Склады; Документ ЗаказКлиента) - их обновлять нельзя. Так же нельзя обновлять свойства.
