### ISSUE TITLE
Проблема 1С КА при синхронизации с CRM

### ISSUE THREAD

**Issue by Mannikc** [retailcrm/1C-configuration#113]
Добрый день.
Интеграция 1С КА с retail
Проблема при подключении, и в дальнейшем при работе. 
Расширение либо для очень старых платформ, либо не понимаю, почему не подхватываются справочники номенклатуры в 1С из CRM. 
+ ко всему заказ покупателя невозможно провести из-за столбца "Ставка НДС", он не заполняется, как бы ты этого не хотел.
Проблема скорее всего в том, что расширение писалось очень давно и не обновляли константы. Не подхватывает некоторые поля в самой 1С.

**Comment by Marina48** [comment]
Добрый день!

Модуль тестировался на платформе 8.3.22.1923, релиз конфигурации 2.5.13.82.

Какой релиз платформы и конфигурации вы используете для проверки работы модуля? А так же сообщите версию самого модуля интеграции.

> ко всему заказ покупателя невозможно провести из-за столбца "Ставка НДС", он не заполняется, как бы ты этого не хотел

Какое значение констант **Налогообложение** и **ЦенаВключаетНДС** вы устанавливаете?

> Проблема скорее всего в том, что расширение писалось очень давно и не обновляли константы. Не подхватывает некоторые поля в самой 1С.

Последние изменения в модуле были 17.10.2023г

**Comment by Marina48** [comment]
Добрый день! Если вопрос еще актуален, направьте нам обращение на почту [support@retailcrm.ru](mailto:support@retailcrm.ru) или создайте его из системы.
