### ISSUE TITLE
Партии и серии товаров

### ISSUE THREAD

**Issue by igorkenzer** [retailcrm/1C-configuration#118]
Добрый день. Планируется ли добавление в обмен документами партий и серий товаров? Многим очень нужны Сроки годности товаров в обмене. И из-за серий (сроков годности) в 1С происходит разбивка строки товара на несколько строк - подбор остатков по серии, и обратно в Ретеил данные не обновляются

**Comment by Marina48** [comment]
Добрый день! Обмен документами партий и серий товаров не реализован в модулях обмена. Вы можете подробно описать свой кейс и направить нам обращение на почту [support@retailcrm.ru](mailto:support@retailcrm.ru) или создать его (обращение) из системы. Обращение будет рассмотрено нашими аналитиками.

Актуальный модуль корректно работает с разделением строки на несколько строк. Данные по разбитым строкам корректно отправляются в RetailCRM, если там включена соответствующая настройка, а так же корректно загружаются в 1С
