### ISSUE TITLE
При загрузке товаров, не передается цена на товар

### ISSUE THREAD

**Issue by Verteletsky** [retailcrm/1C-configuration#29]
Здравствуйте, использую 1С:Предприятие 8.3 (8.3.14.1779) "Управление торговлей", редакция 10.3 (10.3.55.3)

После нажатия на "Загрузить заказы", не выгружается цены со скидкой на товар, получаю цену установленную в 1С. А в системе RetailCRM ONLINE пропадает товар, послу загрузки в 1С

**Comment by Marina48** [comment]
Здравствуйте! Если Ваш вопрос всё ещё актуален, то продублируйте его, пожалуйста, нам на адрес support@retailcrm.ru. Выяснение причин такого поведения потребует уточнения.
