### ISSUE TITLE
Не выгружаются остатки. Ошибка.

### ISSUE THREAD

**Issue by at5eweb** [retailcrm/1C-configuration#35]
Здравствуйте, подскажите пожалуйста в чем может быть причина ошибки "Метод объекта не обнаружен (НайтиПоЗначению)" при попытке выгрузить остатки в RetailCRM ? Платформа: 1С:Предприятие 8.3 (8.3.16.1063)
Конфигурация: Управление торговлей, редакция 11 (11.4.11.102)
Все остальное отлично работает, только с выгрузкой остатков не могу понять в чем дело

**Comment by Marina48** [comment]
Здравствуйте! Следует проверить, заполнена ли вкладка "Склады/Организации" в обработке, при необходимости заполнить. Если Ваш вопрос всё ещё будет актуален, то продублируйте его, пожалуйста, нам на адрес support@retailcrm.ru. Выяснение причин такого поведения потребует уточнения.

**Comment by at5eweb** [comment]
Да заполнена вкладка, все перепроверил. Я уже написал вам на support@retailcrm.ru вчера, ваши специалисты выясняют в чем причина. Спасибо большое!
