### ISSUE TITLE
Привязка оплат

### ISSUE THREAD

**Issue by bartlebi** [retailcrm/1C-configuration#68]
В 1с на вкладке для привязки оплат доступны несколько операций - эквайринг, документ поступления безналичных ДС и ПКО, однако для привязки доступен выбор только эквайрингового терминала, хотя должен быть для ПКО - касса организации, а для поступления без. ДС - расчетный счет.
УТ 11.5.10.52
Последний модуль от 01.12.2022 (2.16.0)

**Comment by Marina48** [comment]
Добрый день! В текущей версии модуля кассу и банковский счет можно выбрать в константах на вкладке "Константы" или, при использовании опции "Несколько организаций", в справочнике "CRM Организации". Привязка кассы и счета непосредственно к типу оплаты не реализована. Если вам необходим такой функционал, направьте нам обращение на почту support@retailcrm.ru или создайте его из системы.
